### ISSUE TITLE
Will it extend the forwarding address to etcd service discovery?

### ISSUE THREAD

**Issue by wisonlau** [jmaister/taronja-gateway#1]
https://github.com/jmaister/taronja-gateway/blob/3cbb657fed635a1b85f9e76bc8bb33afcc85a468/sample/config.yaml#L16

**Comment by jmaister** [comment]
For now, the project is in its early stages, and I haven't fully explored integrating with etcd for service discovery. It's definitely something we can consider as the project evolves and we gather more insights into its needs.

What is your use case?

**Comment by wisonlau** [comment]
> For now, the project is in its early stages, and I haven't fully explored integrating with etcd for service discovery. It's definitely something we can consider as the project evolves and we gather more insights into its needs.
> 
> What is your use case?

Because it is a k8s deployment node, the ip will change, so you need to get the available IP from etcd.

```
name: Example Gateway Configuration
server:
  host: 127.0.0.1
  port: 8080
  url: http://localhost:8080
management:
  prefix: _
routes:
  - name: V1 of the API
    from: /api/v1/*
    removeFromPath: "/api/v1/"
    driver: etcd # todo
    discoveries:
        - name: server_name
          enable: true
          fail-limit: 3
  - name: V2 of the API (authenticated)
    from: /api/v2/*
    removeFromPath: "/api/v2/"
    driver: static // todo
    discoveries:
    to: https://jsonplaceholder.typicode.com
    authentication:
      enabled: true
```
